"""Rename department table

Revision ID: 389e2159e7c1
Revises: 30c5d15ede1b
Create Date: 2025-01-18 13:20:44.853479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389e2159e7c1'
down_revision = '30c5d15ede1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('department', 'departments')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
